# 0
def principal():
    print("     * BITACORAS *")
    print("--------------------------------------------")
    print("    1. Lista general")
    print("--------------------------------------------")
    print("    2. Crear nueva salida")
    print("--------------------------------------------")
    print("    3. Crear nueva entrada")
    print("--------------------------------------------")
    print("    4. Modificar destino")
    print("--------------------------------------------")
    print("    5. Eliminar")
    print("--------------------------------------------")
    print("    6. Salir")
    print("--------------------------------------------")